"use client";

import { AlertTriangle, CalendarClock, Lightbulb, Bot } from "lucide-react";
import type { Insight, InsightType } from "@/types/banking";

interface Props {
  insights: Insight[];
}

const INSIGHT_CONFIG: Record<
  InsightType,
  {
    label: string;
    Icon: React.FC<{ className?: string }>;
    badgeClass: string;
    borderClass: string;
    bgClass: string;
  }
> = {
  spending_anomaly: {
    label: "Anomaly Detected",
    Icon: AlertTriangle,
    badgeClass: "bg-red-100 text-red-700 border-red-200",
    borderClass: "border-l-red-400",
    bgClass: "bg-red-50",
  },
  bill_forecast: {
    label: "Bill Forecast",
    Icon: CalendarClock,
    badgeClass: "bg-blue-100 text-blue-700 border-blue-200",
    borderClass: "border-l-blue-400",
    bgClass: "bg-blue-50",
  },
  saving_tip: {
    label: "Saving Tip",
    Icon: Lightbulb,
    badgeClass: "bg-amber-100 text-amber-700 border-amber-200",
    borderClass: "border-l-amber-400",
    bgClass: "bg-amber-50",
  },
  system_status: {
    label: "System",
    Icon: Bot,
    badgeClass: "bg-gray-100 text-gray-600 border-gray-200",
    borderClass: "border-l-gray-300",
    bgClass: "bg-gray-50",
  },
};

export default function InsightAlerts({ insights }: Props) {
  const activeInsights = insights.filter((i) => i.type !== "system_status");

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-orange-50 rounded-xl flex items-center justify-center">
            <Bot className="w-5 h-5 text-orange-500" />
          </div>
          <div>
            <h2 className="font-semibold text-gray-900">ML Insights Feed</h2>
            <p className="text-xs text-gray-400">Auto-generated by the AI pipeline</p>
          </div>
        </div>
        {activeInsights.length > 0 && (
          <span className="px-2.5 py-1 text-xs font-semibold bg-orange-100 text-orange-700 rounded-full border border-orange-200">
            {activeInsights.length} active
          </span>
        )}
      </div>

      {activeInsights.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-12 text-center">
          <div className="w-12 h-12 bg-gray-100 rounded-2xl flex items-center justify-center mb-3">
            <Bot className="w-6 h-6 text-gray-400" />
          </div>
          <p className="text-sm font-medium text-gray-600">No insights yet</p>
          <p className="text-xs text-gray-400 mt-1">
            Post 3+ transactions to activate the ML pipeline
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {activeInsights.map((insight, i) => {
            const config =
              INSIGHT_CONFIG[insight.type] ?? INSIGHT_CONFIG.system_status;
            const { Icon } = config;

            return (
              <div
                key={insight.id ?? i}
                className={`border-l-4 ${config.borderClass} ${config.bgClass} rounded-r-xl p-4`}
              >
                <div className="flex items-center justify-between gap-2 mb-2">
                  <span
                    className={`inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full border ${config.badgeClass}`}
                  >
                    <Icon className="w-3 h-3" />
                    {config.label}
                  </span>
                  <span className="text-xs text-gray-400 capitalize shrink-0">
                    {insight.category.replace(/_/g, " ")}
                  </span>
                </div>
                <p className="text-sm text-gray-700 leading-relaxed">
                  {insight.message}
                </p>
                {insight.anomaly_score != null &&
                  insight.type === "spending_anomaly" && (
                    <p className="text-xs text-gray-400 mt-2">
                      Amount:{" "}
                      <span className="font-medium text-red-600">
                        Rp {insight.anomaly_score.toLocaleString("id-ID")}
                      </span>
                    </p>
                  )}
                {insight.predicted_date && (
                  <p className="text-xs text-blue-600 font-medium mt-2">
                    Predicted date: {insight.predicted_date}
                  </p>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
